"""add per-key rate limit columns to api_keys

Revision ID: 65d1c1eb115d
Revises: dbcf493426b4
Create Date: 2026-05-31 12:20:51.005283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d1c1eb115d'
down_revision: Union[str, Sequence[str], None] = 'dbcf493426b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('rate_limit_capacity', sa.Integer(), server_default='10', nullable=False))
    op.add_column('api_keys', sa.Column('rate_limit_refill_rate', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'rate_limit_refill_rate')
    op.drop_column('api_keys', 'rate_limit_capacity')
    # ### end Alembic commands ###
