"""add request_logs table

Revision ID: aa3503f65d27
Revises: 65d1c1eb115d
Create Date: 2026-06-01 10:49:25.996593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3503f65d27'
down_revision: Union[str, Sequence[str], None] = '65d1c1eb115d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_value', sa.String(), nullable=False),
    sa.Column('upstream_url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_api_key_value'), 'request_logs', ['api_key_value'], unique=False)
    op.create_index(op.f('ix_request_logs_status_code'), 'request_logs', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_status_code'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_api_key_value'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
